name: "laennec-ai-flutter-cicd"
description: "CI/CD pipeline for Laennec AI Health Assistant Flutter app"

# Trigger configuration
github:
  owner: "geopaul343"  # Replace with your GitHub username
  name: "chatbot_sample_project"   # Replace with your repository name
  push:
    branch: "^main$"

# Build configuration
filename: "cloudbuild.yaml"

# Substitutions
substitutions:
  _BUCKET_NAME: "chatbot_laennec_geo"
  _VERSION_PREFIX: "1.0.3"

# Include in trigger
includedFiles:
  - "lib/**"
  - "android/**"
  - "pubspec.yaml"
  - "cloudbuild.yaml"

# Service account (replace with your service account email)
serviceAccount: "projects/sample-gcp-actions-geo
/serviceAccounts/chatbot-cicd@sample-gcp-actions-geo.iam.gserviceaccount.com" 